
[workspace]
package.version = "0.5.1"
package.edition = "2021"
package.license = "MIT OR Apache-2.0"

[package]
name = "egui-probe"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Trait and derive macro for exposing value editing in egui"

[features]
derive = ["dep:egui-probe-proc"]

[dependencies]
egui-probe-proc = { path = "proc", version = "=0.5.1", optional = true }
egui = { version = "0.29" }

smallvec1 = { package = "smallvec", version = "1", features = [
    "const_generics",
], optional = true }
smallvec2 = { package = "smallvec", version = "2.0.0-alpha.7", optional = true }
hashbrown = { version = "0.15", optional = true }

[dev-dependencies]
eframe = "0.29"
edict = "0.6"

[[example]]
name = "demo"
required-features = ["derive"]

[[example]]
name = "edict"
required-features = ["derive"]
